name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v1
      - name: Setup NodeJs 13.x
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
      - name: Push changes
        uses: actions-go/push@v1

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
